config/routes.rb
Rails.application.routes.draw do
  resources :teachers do
    member do
      resources :assignments, param: "assignment_id"
    end
  end

  resources :students do
    member do
      resources :assignments, param: "assignment_id", only: [:show]
    end
  end

  #root to: 'teachers#index', as: :root
  resources :comments, only: [:new, :create]
  root to: 'teachers#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :student
  has_many :questions
  has_many :comments
  validates :content_link, presence: true
  validates :short_description, presence: true
  validates_format_of :content_link, :with => /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i

  accepts_nested_attributes_for :questions

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :student
  belongs_to :assignment
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :assignment
  has_many :comments
  validates :description, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :assignments
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :assignments
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= Teacher.find(1)
  end

  def render_js_form objects, *params

    locals = {objects: objects}
    if defined?(params) and params.length > 0
      locals = locals.merge *params
    end
    puts locals
    render  partial: 'shared/form_errors',
            locals: locals
  end

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_filter :set_assignment, only: [ :show]
  before_filter :set_user, only: [ :create, :show]

  def index
    @students = Student.all
  end

  def new
    @assignment = Assignment.new

    3.times { @assignment.questions.build }
  end

  def create
    @assignment = Assignment.new assignment_params
    @assignment.teacher = @user
    respond_to do |format|
      if @assignment.save
        format.js { render_js_form [@assignment] }
        format.html { teachers_path }
      else
        format.js { render_js_form [@assignment] }
        format.html { teachers_path }
      end
    end
  end

  def show
    @comment = Comment.new
    @comments = Comment.where('assignment_id=?', @assignment.id).order('created_at DESC')
  end

  private
    def set_assignment
      @assignment = Assignment.find(params[:assignment_id])
    end

    def set_user
      if params[:is_student]
        @user = Student.find(params[:id])
      else
        @user = Teacher.find(params[:id])
      end
    end

    def assignment_params
      params.require(:assignment).permit(
        :content_link,
        :student_id,
        :short_description,
        questions_attributes: [:description]
      )
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @comments = Comment.order('created_at DESC')
  end

  def create
    respond_to do |format|
      @comment = Comment.new(comment_params)
      if @comment.save
        flash.now[:success] = 'Your comment was successfully posted!'
      else
        flash.now[:error] = 'Your comment cannot be saved.'
      end
      format.html {redirect_to root_url}
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :assignment_id, :teacher_id, :student_id)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :set_student, only: [ :show]

  def index
    @students = Student.all
  end

  def show
    @assignments = @student.assignments
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :set_teacher, only: [ :show]

  def index
    @teachers = Teacher.all
  end

  def show
    @assignments = @teacher.assignments
  end

  private
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/assignments/_form.html.haml
= simple_form_for @assignment, remote: true do |f|
  = f.input :content_link
  = f.input :student_id, as: :select, collection: Student.all.map{ |l| [l.name, l.id, {:name => l.name.downcase}] }, include_blank: false
  = f.input :short_description

  = f.simple_fields_for :questions do |qf|
    = 'Question:'
    = qf.input :description

  %button.btn.btn-lg.btn-primary.btn-login.btn-block= 'Create'

app/views/assignments/new.html.haml
= render 'form'

app/views/assignments/show.html.haml
%h1= "Assignment"
%br
= 'Check the link and answer the questions below'
%br
%a{ :href => @assignment.content_link, :title => @assignment.short_description }= @assignment.short_description
%br
%br
%br
- @assignment.questions.each_with_index do | question, i |
  = "Question #{i+1}"
  %br
  .question{id: "question-#{question.id}"}
    %p= question.description

.page-header
  = render 'comments/form'
  .panel.panel-default#comments
    .panel-body
      %ul.media-list
        - @comments.each do | comment |
          = render 'comments/comment', comment: comment

    / :javascript
    /   window.client = new Faye.Client('/faye')
    /   var channel_name = "/questions/#{question.id}";
    /   // Subscribe to the public channel
    /   var public_subscription = client.subscribe(channel_name, function(data) {
    /     $("#question-#{question.id}").find('p').prepend(payload.message)
    /   });
    / - question.comments.each do | comment |
    /   .panel.panel-default
    /     %ul.media-list
    /       %li.media.comment
    /         - if comment.teacher
    /           %b= comment.teacher.name + " says:"
    /         - elsif comment.student
    /           %b= comment.student.name + " says:"
    /         = comment.body
    /   %br
    / .well
    /   = form_for @comment, remote: true do |f|
    /     .form-group
    /       = f.label :question_id, value: question.id
    /       = f.label :body, 'Enter your comment:'
    /       = f.text_area :body, rows: 3, class: 'form-control', required: true, maxlength: 2000
    /     = f.submit 'Post', class: 'btn btn-primary btn-lg'

app/views/comments/_comment.html.haml
%li.media.comment
  - if comment.teacher_id
    %b= comment.teacher.name + ' says: '
  - elsif comment.student_id
    %b= comment.student.name + ' says: '

  = comment.body

app/views/comments/_form.html.haml
.well
  = simple_form_for @comment, remote: true do |f|
    .form-group
      = f.input :assignment_id, as: :hidden, :input_html => { :value => @assignment.id }
      - if @user.class == Student
        = f.input :student_id, as: :hidden, :input_html => { :value => @user.id }
      - else
        = f.input :teacher_id, as: :hidden, :input_html => { :value => @user.id }
      = f.input :body, rows: 3, class: 'form-control', required: true, maxlength: 2000
    = f.submit 'Answer', class: 'btn btn-primary btn-lg'

app/views/comments/create.js.erb
publisher = client.publish("/comments", {
  message: '<%= j render @comment %>'
});

publisher.callback(function() {
  $('#comment_body').val('');
  $('#new_comment').find("input[type='submit']").val('Submit').prop('disabled', false)
});

publisher.errback(function() {
  alert('There was an error while posting your comment.');
});

app/views/comments/new.html.haml
.page-header
  %h1='Join the discussion'
  = render 'form'
  .panel.panel-default#comments
    .panel-body
      %ul.media-list
        = render @comments

app/views/layouts/_head.html.haml
%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}

%meta{"http-equiv" => "X-UA-Compatible", "content" => "IE=edge"}
= raw '<link rel="icon" type="image/png" href="'+ image_path('favicon.png') +'" />'

= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
= javascript_include_tag "application", "data-turbolinks-track" => true

= csrf_meta_tags

- if protect_against_forgery?
  = javascript_tag "var AUTH_TOKEN = '#{form_authenticity_token}';"

/[if lt IE 9]
  %script{ :src => "http://html5shiv.googlecode.com/svn/trunk/html5.js" }
  = javascript_include_tag "respond", "data-turbolinks-track" => false

app/views/layouts/_menu.html.haml
%nav.navbar
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path}
        = "Add Logo"
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li=link_to 'Teachers', teachers_path
        %li=link_to 'Students', students_path

app/views/layouts/application.html.haml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if lt IE 7 ]> <html class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html class=""> <!--<![endif]-->
%head
  = render 'layouts/head'

%body
  .header-container
    .inside-header-container
      = render 'layouts/menu'
  .container#primary-content
    - flash.each do |key, value|
      .alert.alert-
        = value
    = yield

app/views/questions/_form.html.haml
= f.simple_fields_for :questions do |question|
  = render 'question_fields', :f => question
.links
  = link_to_add_association 'add task', f, :tasks

app/views/questions/_question_fields.html.haml
.nested-fields
  = f.input :description
  = f.check_box :_destroy
  = f.label :_destroy, "Remove Question"

app/views/shared/_form_errors.js.erb
// You have to send html id of the form so we know where should we dispay errors.
// id of the form should be set on form and inside hidden field (double check html)
<%
  errors_by_entity = {}
  if defined? objects
    objects.each_with_index do |obj, index|
      key = obj.class.name.tableize.singularize
      puts key
      if defined?(custom_mapping) && custom_mapping[index]
        key = custom_mapping[index]
      end
      puts obj.errors
      errors_by_entity[key] = obj.errors
    end
  else
    errors_by_entity = {obj_type => @errors}
  end
%>

var formObj = window.last_submitted_form;
formObj.find("div.errors").remove(); // remove errors below input fields
formObj.find(".error").removeClass("error"); // remove class on input fields
<%
  if defined? add_class
    %>
      formObj.addClass("<%= add_class %>");
    <%
  end
%>

<%= raw(js) if defined? js %>

var errors_by_entity = <%= raw(errors_by_entity.to_json) %>;

var has_errors = false;

for (key in errors_by_entity) {
  //alert(JSON.stringify(errors_by_entity[key]));
  if (Object.keys(errors_by_entity[key]).length > 0) {
    has_errors = true;
    break;
  }
}

if(has_errors) {
  // form is submitted - remove all error marks on input fields
  formObj.removeClass("saved");

  for (var obj_type in errors_by_entity) {
    errors = errors_by_entity[obj_type];
    for (var key in errors){
      var key_splitted_array = key.split(".");
      var final_key = key_splitted_array[key_splitted_array.length - 1]
      var error = errors[key];

      var input = "";
      if(key_splitted_array.length == 2 && false) {
        input = formObj.find("#"+ obj_type + "_" +key_splitted_array[0]+"_attributes_"+key_splitted_array[1]);
      } else if(key_splitted_array.length > 2) {
        long_key_id = "#"+ key_splitted_array[0] + "_" +key_splitted_array[1]+"_attributes_"+key_splitted_array[2] + "_" + key_splitted_array[3];
        input = formObj.find(long_key_id);
      } else {
        input = formObj.find("[name='"+ obj_type + "[" + final_key +"]']");
        if (input.size() == 0) {
          input = formObj.find("[name='"+ obj_type + "[" + final_key +"_id]']"); // TODO: could we know if this is relation more easily?
        }
      }
      // var input = formObj.find("#"+ obj_type + "_" +key);

      var obj = input.closest(".form-group");

      obj.find(".form-control").addClass("error");

      if(obj.find(".errors").size() == 0) {
        obj.append("<div class='errors'></div>")
      }

      obj.find("div.errors").append("<div class='error'>"+error[0]+"</div>"); // we append only first error
    }
  }

  var l = 5;
  for( var i = 0; i < 10; i++ ) {
    $(formObj).find("div.errors").parent().animate( { 'margin-left': "+=" + ( l = -l ) + 'px', 'margin-right': ( -l ) + 'px', }, 50);
  }

  setTimeout(function() { $(formObj).find("div.errors").parent().attr("style", ""); }, 610)


  <% if defined? flash_message %>
     flash_message("danger", '<%= flash_message %>');
  <% end %>

  <%= raw(js_on_error) if defined? js_on_error %>
} else {
  formObj.addClass("saved");

  <%= raw(js_on_success) if defined? js_on_success %>


}

app/views/students/index.html.haml
%h1='Students list'
.content
  %ul.list-group
    - @students.each do | student |
      %li.list-group-item
        = link_to student.name, student

app/views/students/show.html.haml
%h1= @student.name + ' ( ' + @student.student_id + ' )'
.content
  %ul.list-group
    - @assignments.each do | assignment |
      %li.list-group-item
        = link_to assignment.short_description, assignment_path(id: @student.id, assignment_id: assignment.id, is_student: true)

app/views/teachers/index.html.haml
%h1='Teachers list'
.content
  %ul.list-group
    - @teachers.each do | teacher |
      %li.list-group-item
        = link_to teacher.name, teacher

app/views/teachers/show.html.haml
%h1= @teacher.name + ' ( ' + @teacher.email + ' )'
= link_to 'Create new assignment', new_assignment_path, class: 'btn btn-default'
.content
  %ul.list-group
    - @assignments.each do | assignment |
      %li.list-group-item
        = link_to assignment.short_description, assignment_path(id: @teacher.id, assignment_id: assignment.id)